<a href="https://colab.research.google.com/github/AlmiraRahman/tugasMachineLearning/blob/main/Week9_3_3Concise_Impementation_of_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!pip install d2l==0.17.0

In [13]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [14]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [15]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 0.83129275, -0.00933762],
        [ 0.3234113 , -0.45649365],
        [-0.09551334, -0.6764237 ],
        [-0.60193294,  0.72908145],
        [-1.1406227 ,  0.6143253 ],
        [ 0.88728577,  1.7580591 ],
        [-0.85323954,  1.2862418 ],
        [-0.24962795, -1.9006847 ],
        [-0.44801843, -0.45342684],
        [-1.0255653 , -0.12156022]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 5.8809304e+00],
        [ 6.3944426e+00],
        [ 6.2950144e+00],
        [ 5.1600748e-01],
        [-1.6146627e-01],
        [-9.9935262e-03],
        [-1.8763485e+00],
        [ 1.0157993e+01],
        [ 4.8347554e+00],
        [ 2.5510244e+00]], dtype=float32)>)

In [16]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [17]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [18]:
loss = tf.keras.losses.MeanSquaredError()

In [19]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [20]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000266
epoch 2, loss 0.000094
epoch 3, loss 0.000095


In [21]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([-1.7850399e-03 -5.6982040e-05], shape=(2,), dtype=float32)
error in estimating b [0.00025702]
